## Importing Packages

python scripts/reformat_fleury.py --datadir data --rename data/rename_columns.xlsx --correction data/fix_values.xlsx --output combined_hla.tsv

In [1]:
import pandas as pd
import os

## Loading Data

In [2]:
def load_table(file, separator=None):
    df = ''
    if str(file).split('.')[-1] == 'tsv':
        separator = '\t' if separator is None else separator
        df = pd.read_csv(file, encoding='latin-1', sep=separator, dtype='str')
    elif str(file).split('.')[-1] == 'csv':
        separator = ',' if separator is None else separator
        df = pd.read_csv(file, encoding='latin-1', sep=separator, dtype='str')
    elif str(file).split('.')[-1] in ['xls', 'xlsx']:
        df = pd.read_excel(file, index_col=None, header=0, sheet_name=0, dtype='str')
        df.fillna('', inplace=True)
    else:
        print('Wrong file format. Compatible file formats: TSV, CSV, XLS, XLSX')
        exit()
    return df

In [3]:
BASE_PATH = '../data/FLEURY/'
dfs = []

for file in os.listdir(BASE_PATH):
    if file.endswith(('.csv', '.tsv')):
        print(file)
        df = load_table(BASE_PATH + file, separator='\t')
        dfs.append(df)

20230807_GrupoFleury_Virusrespiratorios - 31-07-2023 a 06-08-2023_SE31.tsv
20230529_GrupoFleury_Virusrespiratorios - 22-05-2023 a 28-05-2023_SE21.tsv
22_06_GrupoFleury_Virusrespiratorios - 01-06-2022 a 30-06-2022.csv
23_03_GrupoFleury_Virusrespiratorios - 01-03-2023 a 31-03-2023.csv
20230522_GrupoFleury_Virusrespiratorios - 15-05-2023 a 21-05-2023_SE20.tsv
22_11_GrupoFleury_Virusrespiratorios - 01-11-2022 a 30-11-2022.csv
22_07_GrupoFleury_Virusrespiratorios - 01-07-2022 a 31-07-2022.csv
23_04_GrupoFleury_Virusrespiratorios - 01-04-2023 a 30-04-2023.csv
23_02_GrupoFleury_Virusrespiratorios - 01-02-2023 a 28-02-2023.csv
22_05_GrupoFleury_Virusrespiratorios - 01-05-2022 a 31-05-2022.csv
20230515_GrupoFleury_Virusrespiratorios - 08-05-2023 a 14-05-2023_SE19.tsv
20230731_GrupoFleury_Virusrespiratorios - 24-07-2023 a 30-07-2023_SE30.tsv
22_12_GrupoFleury_Virusrespiratorios - 01-12-2022 a 31-12-2022.csv
22_09_GrupoFleury_Virusrespiratorios - 01-09-2022 a 30-09-2022.csv
20230703_GrupoFleury_Virusrespiratorios - 26-06-2023 a 02-07-2023_SE26.tsv
20230626_GrupoFleury_Virusrespiratorios - 19-06-2023 a 25-06-2023_SE25.tsv
20230605_GrupoFleury_Virusrespiratorios - 29-05-2023 a 04-06-2023_SE22.tsv
20230619_GrupoFleury_Virusrespiratorios - 12-06-2023 a 18-06-2023_SE24.tsv
22_03_GrupoFleury_Virusrespiratorios - 01-03-2022 a 31-03-2022.csv
22_04_GrupoFleury_Virusrespiratorios - 01-04-2022 a 30-04-2022.csv
20230724_GrupoFleury_Virusrespiratorios - 17-07-2023 a 23-07-2023_SE29.tsv
20230510_GrupoFleury_Virusrespiratorios - 01-05-2023 a 07-05-2023_SE18.tsv
23_01_GrupoFleury_Virusrespiratorios - 01-01-2023 a 31-01-2023.csv
22_10_GrupoFleury_Virusrespiratorios - 01-10-2022 a 31-10-2022.csv
22_01_GrupoFleury_Virusrespiratorios - 01-01-2022 a 31-01-2022.csv
22_02_GrupoFleury_Virusrespiratorios - 01-02-2022 a 28-02-2022.csv
20230717_GrupoFleury_Virusrespiratorios - 10-07-2023 a 16-07-2023_SE28.tsv
22_08_GrupoFleury_Virusrespiratorios - 01-08-2022 a 31-08-2022.csv
20230612_GrupoFleury_Virusrespiratorios - 05-06-2023 a 11-06-2023_SE23.tsv
20230710_GrupoFleury_Virusrespiratorios - 03-07-2023 a 09-07-2023_SE27.tsv

In [4]:
df_fleury = pd.concat(dfs)

### EDA

In [5]:
df_fleury.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1293183 entries, 0 to 3704
Data columns (total 10 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   CODIGO REQUISICAO  1293183 non-null  object
 1   DATA COLETA        1293154 non-null  object
 2   PACIENTE           1293154 non-null  object
 3   SEXO               1293154 non-null  object
 4   IDADE              1293142 non-null  object
 5   MUNICIPIO          1293154 non-null  object
 6   ESTADO             1293154 non-null  object
 7   EXAME              1293154 non-null  object
 8   PATOGENO           1293154 non-null  object
 9   RESULTADO          1293154 non-null  object
dtypes: object(10)
memory usage: 108.5+ MB

In [6]:
df_fleury.columns

Index(['CODIGO REQUISICAO', 'DATA COLETA', 'PACIENTE', 'SEXO', 'IDADE',
       'MUNICIPIO', 'ESTADO', 'EXAME', 'PATOGENO', 'RESULTADO'],
      dtype='object')

In [7]:
df_fleury.shape

(1293183, 10)

In [8]:
df_fleury.head()

,CODIGO REQUISICAO,DATA COLETA,PACIENTE,SEXO,IDADE,MUNICIPIO,ESTADO,EXAME,PATOGENO,RESULTADO
0,1000964200_500,31/07/2023,F7631D38436612E1B04DF63D552E0D8E,F,29,COTIA,SP,2019NCOV,"Covid 19, Detecção por PCR",NÃO DETECTADO (NEGATIVO)
1,1421754470_800,31/07/2023,06EEE3655339C91C09D6F8B45FE24A3B,M,67,SAO PAULO,SP,2019NCOV,"Covid 19, Detecção por PCR",NÃO DETECTADO (NEGATIVO)
2,1421754512_200,31/07/2023,DA77C19BF2BBA8928A78EB95EC3DB44B,F,51,SAO PAULO,SP,2019NCOV,"Covid 19, Detecção por PCR",NÃO DETECTADO (NEGATIVO)
3,1421754547_100,31/07/2023,0A6A0B135E017233C2A233E2A3C299B2,M,69,SAO PAULO,SP,2019NCOV,"Covid 19, Detecção por PCR",NÃO DETECTADO (NEGATIVO)
4,1421754569_100,31/07/2023,27281A15BB1CFFEF5771DE1E69DC69EE,F,34,SAO PAULO,SP,2019NCOV,"Covid 19, Detecção por PCR",NÃO DETECTADO (NEGATIVO)

Show unique values in the columns

In [9]:
columns_show_unique_values = ["PACIENTE", "SEXO", "IDADE", "MUNICIPIO", "ESTADO", "EXAME", "PATOGENO", "RESULTADO"]

for column in columns_show_unique_values:
    print(f"Column: {column}")
    print(f"Unique values: {df[column].unique()}")
    print()

Column: PACIENTE
Unique values: ['AC00020512A8A4E9C688369F48CC50C0' 'A661A1082E27E7B94C3071F66F750EDC'
 '5602D570ECC4438A7417CE76B735667F' ... '552B1BB28656EC3F81DFEC63F8D073E3'
 'B6D9786CDE6BA7A40E23939FCF800CF7' nan]

Column: SEXO
Unique values: ['F' 'M' nan]

Column: IDADE
Unique values: ['48' '37' '55' '76' '30' '60' '35' '29' '26' '52' '65' '62' '58' '59'
 '36' '39' '78' '54' '42' '44' '31' '43' '12A10M' '27' '45' '14A6M' '3A1M'
 '6A10M' '61' '10A3M' '86' '64' '33' '9M2D' '7M25D' '1A11M' '3M6D' '2A8M'
 '1A3M' '87' '18A11M' '56' '24' '51' '38' '16A10M' '66' '57' '46' '70'
 '40' '34' '47' '49' '63' '83' '2A2M' '67' '7M7D' '6M29D' '50' '68' '28'
 '89' '25' '32' '23' '11A11M' '8A4M' '73' '74' '8A9M' '71' '6M22D' '72'
 '91' '84' '80' '75' '5A9M' '88' '79' '53' '11A5M' '41' '4M19D' '1A2M'
 '90' '19A5M' '22' '1A1M' '6M16D' '2M22D' '5A10M' '8M20D' '5M20D' '77'
 '19A2M' '4M27D' '81' '5A7M' '4A8M' '3A7M' '94' '20A2M' '20A1M' '69' '21'
 '20A10M' '14A4M' '4A4M' '10A5M' '10M26D' '2A7M' '19A11M' '93' '7A'
 '11M24D' '7M0D' '16A1M' '4M9D' '4A5M' '1A4M' '15A2M' '11A3M' '18A7M'
 '15A9M' '19A3M' '18A9M' '17A10M' '18A4M' '9A3M' '3M8D' '4M5D' '7M10D'
 '11A7M' '14A8M' '19A6M' '5A5M' '2A11M' '4A1M' '1A10M' '3A10M' '2A9M'
 '4A6M' '4A2M' '95' '5A' '7A8M' '82' '9A5M' '7A2M' '15A10M' '9A11M' '6A8M'
 '11M16D' '100' '10M8D' '8A5M' '9A2M' '19A1M' '18A5M' '20A6M' '19A7M'
 '17A2M' '3A4M' '14A5M' '8A' '20A8M' '5A4M' '17A4M' '17A11M' '9A1M' '19A'
 '11A1M' '6A5M' '20A5M' '5A6M' '16A2M' '17A5M' '16A' '5A1M' '15A11M'
 '7M21D' '20A7M' '3A6M' '4M23D' '20A9M' '85' '14A7M' '10A2M' '5A2M'
 '13A10M' '10A11M' '8A6M' '6A4M' '1A9M' '12A4M' '9A4M' '6A' '8A1M' '19A9M'
 '17A9M' '9A7M' '13A3M' '2A10M' '1A5M' '11M29D' '4A3M' '20A4M' '6M14D'
 '1A6M' '2A5M' '8M4D' '1A7M' '7A6M' '8M19D' '3A5M' '10A6M' '9M14D' '4A7M'
 '2M18D' '3A' '10A' '2M17D' '9M6D' '2A1M' '5M27D' '1A' '92' '2A3M' '3A3M'
 '2A4M' '3A11M' '7A3M' '10A8M' '13A1M' '4M15D' '1M1D' '6A2M' '4M11D'
 '2M9D' '6A3M' '17A' '9M22D' '10M28D' '12A' '3A8M' '6M5D' '5M17D' '5M3D'
 '8M22D' '6M20D' '6M18D' '4M8D' '4M2D' '12A5M' '10A9M' '12A7M' '6A1M'
 '4A10M' '19A8M' '10A1M' '12A1M' '13A11M' '13A2M' '6A11M' '1A8M' '4M25D'
 '6M27D' '5M21D' '11M6D' '8M1D' '1M11D' '9M9D' '5A11M' '9A' '8A11M' '2A6M'
 '9A10M' nan]

Column: MUNICIPIO
Unique values: ['SAO PAULO' 'MOGI DAS CRUZES' 'GUARUJA' 'BARUERI' 'CURITIBA'
 'SAO JOSE DOS PINHAIS' 'RECIFE' 'OLINDA' 'PORTO ALEGRE' 'PAULINIA'
 'CAMPINAS' 'HORTOLANDIA' 'MONTE MOR' 'BRASILIA' 'GOIANESIA' 'DIADEMA'
 'OSASCO' 'GOIANIA' 'RIBEIRAO PIRES' 'ARUJA' 'IJUI' 'SANTO ANDRE'
 'SALVADOR' 'AMERICANA' 'ITAPECERICA DA SERRA' 'CARAPICUIBA' 'BAURU'
 'MAUA' 'MANAUS' 'SAO BERNARDO DO CAMPO' 'RIO DE JANEIRO' 'NITEROI'
 'DUQUE DE CAXIAS' 'NILOPOLIS' 'BELFORD ROXO' 'SANTANA DE PARNAIBA'
 'CORTES' 'CABO DE SANTO AGOSTINHO' 'ITUPEVA' 'MAIRINQUE'
 'TABOAO DA SERRA' 'GUARULHOS' 'JABOATAO DOS GUARARAPES' 'SAPUCAIA DO SUL'
 'GRAVATAI' 'MAIRIPORA' 'EMBU DAS ARTES' 'COTIA' 'VITORIA DA CONQUISTA'
 'FERRAZ DE VASCONCELOS' 'PROPRIA' 'PARAISO DO TOCANTINS'
 'SAO MIGUEL DO OESTE' 'COMODORO' 'ARACAJU' 'ITAPEVI' 'MIRASSOL' 'JUNDIAI'
 'BOITUVA' 'SANTOS' 'ALMIRANTE TAMANDARE' 'SAO LOURENCO DA MATA' 'CANOAS'
 'VIAMAO' 'INDAIATUBA' 'JACAREI' 'SAO CAETANO DO SUL' 'CANAPOLIS'
 'RIO BRANCO' 'PINDAMONHANGABA' 'RESENDE' 'CAJAMAR' 'SANTAREM'
 'SAO GONCALO DO SAPUCAI' 'ITAQUAQUECETUBA' 'BOA VISTA'
 "SAO JOAO D'ALIANCA" 'CUBATAO' 'CABEDELO' 'NATAL'
 'VARGEM GRANDE PAULISTA' 'COLOMBO' 'JAGUARIUNA' 'MOGI MIRIM'
 'CHAPADAO DO SUL' 'FLORIANOPOLIS' 'SAO MIGUEL ARCANJO' 'CAMPO GRANDE'
 'VALINHOS' 'CAIEIRAS' 'IMPERATRIZ' 'JACUPIRANGA' 'VINHEDO' 'TAUBATE'
 'SUZANO' 'PAULISTA' 'SAO LUIS' 'AGUAS DE LINDOIA' 'EMBU-GUACU' 'CABREUVA'
 'ALVORADA' 'GUAIBA' 'AMPARO' 'SAO GONCALO' 'NOVA IGUACU' 'JOINVILLE'
 'BALNEARIO BARRA DO SUL' 'SAO FRANCISCO DO SUL' 'ITATIBA' 'MESQUITA'
 'CIDADE OCIDENTAL' 'CEU AZUL' 'ABREU E LIMA' 'GARUVA' 'CHAPADINHA'
 'ARROIO DOS RATOS' 'SAO JOAO DE MERITI' 'ARAQUARI'
 'SANTA BARBARA D OESTE' 'PLANALTINA' 'LAURO DE FREITAS' 'SALTO' 'SUMARE'
 'PIRACICABA' 'CAPIVARI' 'UBATUBA' 'SANTO ANTONIO DE POSSE'
 'SETOR HABITACIONAL JARDIM BOTANICO' 'SOROCABA' 'COSMOPOLIS' 'JANDIRA'
 'LOUVEIRA' 'LIMEIRA' 'PEDREIRA' 'AVARE' 'SAO VICENTE' 'FERNANDOPOLIS'
 'ANANINDEUA' nan]

Column: ESTADO
Unique values: ['SP' 'PR' 'PE' 'RS' 'DF' 'GO' 'BA' 'AM' 'RJ' 'SE' 'TO' 'SC' 'MT' 'MG'
 'AC' 'PA' 'RR' 'PB' 'RN' 'MS' 'MA' nan]

Column: EXAME
Unique values: ['2019NCOV' 'AGCOVIDNS' 'AGINFLU' 'AGSINCURG' 'COVIDFLURSVGX' 'COVID19GX'
 'COVID19SALI' 'INFLUENZAPCR' 'VIRUSMOL' 'VRSAG' nan]

Column: PATOGENO
Unique values: ['Covid 19, Detecção por PCR' 'Covid 19, Antígeno, teste rápido'
 'Influenza A e B - teste rápido' 'Vírus respiratório - Sincicial'
 'Covidflursvgx - SARS-CoV-2' 'Covidflursvgx - Influenza A'
 'Covidflursvgx - Influenza B'
 'Covidflursvgx - Vírus Sincicial Respiratório'
 'Vírus Influenza A (Sazonal)' 'Virusmol, Adenovírus'
 'Virusmol, Coronavírus 229E' 'Virusmol, Coronavírus HKU1'
 'Virusmol, Coronavírus NL63' 'Virusmol, Coronavírus OC43'
 'Virusmol, Metapneumovírus Humano' 'Virusmol, Rinovírus/Enterovírus'
 'Virusmol, Influenza A' 'Virusmol, Influenza A/H1'
 'Virusmol, Influenza A/H1-2009' 'Virusmol, Influenza A/H3'
 'Virusmol, Influenza B' 'Virusmol, Parainfluenza 1'
 'Virusmol, Parainfluenza 2' 'Virusmol, Parainfluenza 3'
 'Virusmol, Parainfluenza 4' 'Virusmol, Vírus Sincicial Respiratório'
 'Virusmol, Bordetella parapertussis' 'Virusmol, Bordetella pertussis'
 'Virusmol, Chlamydophila pneumoniae' 'Virusmol, SARS-CoV-2'
 'Virusmol, Mycoplasma pneumoniae' 'Vírus Sincial Respiratório' nan]

Column: RESULTADO
Unique values: ['NÃO DETECTADO (NEGATIVO)' 'DETECTADO (POSITIVO)' 'NEGATIVO'
 'Influenza B - POSITIVO' 'Influenza A - POSITIVO' 'POSITIVO' nan]

Verificando as duplicatas no codigo requisicao

In [10]:
column_test_uniqueness = ["CODIGO REQUISICAO",]

(
    df_fleury
    .assign(
        duplicated=df_fleury.duplicated(subset=column_test_uniqueness)
    )
    .query("duplicated == True")
    .groupby(column_test_uniqueness)
    .size()
)

CODIGO REQUISICAO
1000859507_300     20
1000859537_2700    20
1000859597_300     20
1000860316_100     20
1000860680_100     20
                   ..
9460004078_100      3
9460004430_500      3
9460006175_100     20
9480001109_1500    20
9480002512_100     20
Length: 12658, dtype: int64

Verificando quantas vezes os códigos se repetem

In [11]:
(
    df_fleury
    .assign(
        duplicated=df_fleury.duplicated(subset=column_test_uniqueness)
    )
    .query("duplicated == True")
    .groupby(column_test_uniqueness)
    .size()
    .unique()
)

array([20,  3,  1, 21])

In [12]:
df_fleury.query("`CODIGO REQUISICAO` == '1000859507_300'")

,CODIGO REQUISICAO,DATA COLETA,PACIENTE,SEXO,IDADE,MUNICIPIO,ESTADO,EXAME,PATOGENO,RESULTADO
264366,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Adenovírus",NEGATIVO
264367,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Coronavírus 229E",NEGATIVO
264368,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Coronavírus HKU1",NEGATIVO
264369,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Coronavírus NL63",NEGATIVO
264370,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Coronavírus OC43",NEGATIVO
264371,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Metapneumovírus Humano",NEGATIVO
264372,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Rinovírus/Enterovírus",NEGATIVO
264373,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Influenza A",NEGATIVO
264374,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Influenza A/H1",NEGATIVO
264375,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Influenza A/H1-2009",NEGATIVO
264376,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Influenza A/H3",NEGATIVO
264377,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Influenza B",NEGATIVO
264378,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Parainfluenza 1",NEGATIVO
264379,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Parainfluenza 2",NEGATIVO
264380,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Parainfluenza 3",NEGATIVO
264381,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Parainfluenza 4",NEGATIVO
264382,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Vírus Sincicial Respiratório",NEGATIVO
264383,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Bordetella parapertussis",NEGATIVO
264384,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Bordetella pertussis",NEGATIVO
264385,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Chlamydophila pneumoniae",NEGATIVO
264386,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, SARS-CoV-2",POSITIVO

In [13]:
df_fleury.fillna("").query("PATOGENO.str.startswith('Influenza')", engine='python').sort_values(by='CODIGO REQUISICAO')

,CODIGO REQUISICAO,DATA COLETA,PACIENTE,SEXO,IDADE,MUNICIPIO,ESTADO,EXAME,PATOGENO,RESULTADO
206477,1000853609_200,02/01/2022,F9C2C481D5AF526B5B6DFB520CD4AE6C,M,51,SAO PAULO,SP,AGINFLU,Influenza A e B - teste rápido,Influenza A - POSITIVO
206478,1000853652_200,02/01/2022,EC8A4F2E24E13EECCF1DFD95C41E32B5,F,32,SAO PAULO,SP,AGINFLU,Influenza A e B - teste rápido,Influenza A - POSITIVO
206479,1000853654_100,02/01/2022,6920A67A5654807D32407D818040EEC3,M,33,BARUERI,SP,AGINFLU,Influenza A e B - teste rápido,NEGATIVO
209651,1000853671_200,04/01/2022,B16A33326455AE572F399B6239AE5F57,F,21,BARUERI,SP,AGINFLU,Influenza A e B - teste rápido,NEGATIVO
207563,1000853762_100,03/01/2022,D0C7FEB44575CDAA15DF99AB9838AFA2,F,22,BARUERI,SP,AGINFLU,Influenza A e B - teste rápido,NEGATIVO
...,...,...,...,...,...,...,...,...,...,...
933,9469900446_100,25/07/2023,FCB8373B792E71B9D48D60FD8023A576,M,62,PRAIA GRANDE,SP,AGINFLU,Influenza A e B - teste rápido,NEGATIVO
934,9480000396_200,25/07/2023,EE20A64E0AFBF1E4327D5AA69E835CF6,F,25,SAO PAULO,SP,AGINFLU,Influenza A e B - teste rápido,NEGATIVO
935,9480000496_100,25/07/2023,1F0FA4DE8DD51CE3A95FC6DCF7FD8D65,M,42,SAO PAULO,SP,AGINFLU,Influenza A e B - teste rápido,NEGATIVO
1004,9480000760_200,26/07/2023,47479AB682947788DFA471FAA48DA9C8,F,45,SAO PAULO,SP,AGINFLU,Influenza A e B - teste rápido,NEGATIVO
1137,9480001344_100,28/07/2023,BF44056BF635F1D59796A587C7F5145B,F,44,SAO PAULO,SP,AGINFLU,Influenza A e B - teste rápido,NEGATIVO

In [14]:
df_fleury.fillna("").query("PATOGENO.str.startswith('Influenza')", engine='python')['RESULTADO'].unique()

array(['NEGATIVO', 'Influenza A - POSITIVO', 'Influenza B - POSITIVO',
       'INCONCLUSIVO', 'Influenza A e B - POSITIVO'], dtype=object)

- 1 - Corrigir idade
- 2 - Tratamento de testes de Influenza A e B
    - Influenza A e B - teste rápido -> [Influenza A, Influenza B] -> EXPLODE -> Corrige resultado
- 5 - Normalizar resultados
- 3 - Normalizar nome dos patogenos
- 4 - Normalizar nome dos testes
- 6 - Agregar resultados

In [15]:
import re
import numpy as np

### Drop NaN

In [16]:
df_fleury_fixed = df_fleury.dropna(subset=["CODIGO REQUISICAO", "DATA COLETA", "IDADE"]).reset_index(drop=True)

### Corrigindo idade

In [17]:
df_fleury['IDADE'].replace(re.compile(r'\d'), 'x').unique()

array(['xx', 'xAxM', 'xxA', 'xxAxM', 'xAxxM', 'xMxxD', 'xA', 'xxAxxM',
       'xMxD', 'xxD', 'xD', 'xxMxxD', nan, 'xxMxD', 'xxx', '-xAxxM'],
      dtype=object)

In [ ]:
fix_age_fleury = (
    lambda age: -1
    if age in (None, np.nan)
    else int(age.split("A")[0])
    if "A" in age
    else 0
    if "D" in age
    else 0
)

In [18]:
def fix_idade_fleury(idade):
    if idade in [np.nan, None]:
        return -1
    if 'A' in idade:
        return int(idade.split('A')[0])
    if idade[-1] == 'D':
        return 0
    return int(idade)

In [19]:
df_fleury_fixed = df_fleury_fixed.assign( **{'IDADE': df_fleury_fixed['IDADE'].apply(fix_idade_fleury)  } )

### Tratamento de testes de Influenza A e B

In [20]:
df_fleury_fixed = (
    df_fleury_fixed
    .assign(
        PATOGENO=df_fleury_fixed["PATOGENO"].mask(
            lambda patogeno: patogeno.fillna("").str.startswith("Influenza A e B"),
            "Influenza A;Influenza B",
        )
    )
    .assign(PATOGENO=lambda df: df["PATOGENO"].str.split(";"))
    .explode("PATOGENO")
    # .query('PATOGENO == "Influenza A" or PATOGENO == "Influenza B"')
)

### Correção do resultado

In [21]:
# UPPERCASE
df_fleury_fixed['RESULTADO'] = df_fleury_fixed['RESULTADO'].str.upper()
df_fleury_fixed['RESULTADO'] = df_fleury_fixed['RESULTADO'].fillna('NT')
df_fleury_fixed['RESULTADO'] = df_fleury_fixed['RESULTADO'].replace('P O S I T I V O', 'POSITIVO')
df_fleury_fixed['RESULTADO'] = df_fleury_fixed['RESULTADO'].str.strip()
df_fleury_fixed['RESULTADO'].unique()

array(['NÃO DETECTADO (NEGATIVO)', 'DETECTADO (POSITIVO)', 'INCONCLUSIVO',
       'NEGATIVO', 'INFLUENZA A - POSITIVO', 'INFLUENZA B - POSITIVO',
       'POSITIVO', 'INFLUENZA A E B - POSITIVO',
       'NÏ¿½O DETECTADO (NEGATIVO)'], dtype=object)

In [22]:
"NÃO DETECTADO (NEGATIVO)",
"NEGATIVO",
"NÏ¿½O DETECTADO (NEGATIVO)",

"DETECTADO (POSITIVO)",
"INFLUENZA A E B - POSITIVO",
"INFLUENZA A - POSITIVO",
"INFLUENZA B - POSITIVO",
"POSITIVO",

"INCONCLUSIVO",
"NT",

## Correção dos exames de INFLUENZA A e B
df_fleury_fixed['RESULTADO'] = df_fleury_fixed.apply(
    lambda row: 'POSITIVO' if
        (
            row['RESULTADO'].startswith('INFLUENZA A e B')
        ) or
        (
            row['PATOGENO'] == 'Influenza A' and row['RESULTADO'].startswith('INFLUENZA A')
        ) or
        (
            row['PATOGENO'] == 'Influenza B' and row['RESULTADO'].startswith('INFLUENZA B')
        )
        else row['RESULTADO']
    , axis=1
)


df_fleury_fixed['RESULTADO'] = df_fleury_fixed['RESULTADO'].apply(
    lambda x: 'Neg' if 'NEGATIVO' in x else 'Pos' if 'POSITIVO' in x else 'NT'
)

In [23]:
'Covid 19, Detecção por PCR' 
'Covid 19, Antígeno, teste rápido'

'Influenza A e B - teste rápido' 
'Vírus Influenza A (Sazonal)'

'Vírus respiratório - Sincicial'
'Vírus Sincial Respiratório'

'Covidflursvgx - SARS-CoV-2' 
'Covidflursvgx - Influenza A'
'Covidflursvgx - Influenza B'
'Covidflursvgx - Vírus Sincicial Respiratório'

'Virusmol, Adenovírus'
'Virusmol, Coronavírus 229E' 
'Virusmol, Coronavírus HKU1'
'Virusmol, Coronavírus NL63' 
'Virusmol, Coronavírus OC43'
'Virusmol, Metapneumovírus Humano' 
'Virusmol, Rinovírus/Enterovírus'
'Virusmol, Influenza A' 
'Virusmol, Influenza A/H1'
'Virusmol, Influenza A/H1-2009' 
'Virusmol, Influenza A/H3'
'Virusmol, Influenza B' 
'Virusmol, Parainfluenza 1'
'Virusmol, Parainfluenza 2' 
'Virusmol, Parainfluenza 3'
'Virusmol, Parainfluenza 4' 
'Virusmol, Vírus Sincicial Respiratório'
'Virusmol, Bordetella parapertussis' 
'Virusmol, Bordetella pertussis'
'Virusmol, Chlamydophila pneumoniae' 
'Virusmol, SARS-CoV-2'
'Virusmol, Mycoplasma pneumoniae'

'Virusmol, Mycoplasma pneumoniae'

In [24]:
PATHOGEN_NORMALIZATION_DICT = {
    "FLUA": {
        "Covidflursvgx - Influenza A",
        "Virusmol, Influenza A",
        "Virusmol, Influenza A/H1",
        "Virusmol, Influenza A/H1-2009",
        "Virusmol, Influenza A/H3",
        "Vírus Influenza A (Sazonal)",
        "Vï¿½rus Influenza A (Sazonal)",
        "Vírus respiratórios - Influenzavirus A",
    },
    "FLUB": {
        "Covidflursvgx - Influenza B",
        "Virusmol, Influenza B",
        "Vírus respiratórios - Influenzavirus B",
    },
    "VSR": {
        "Covidflursvgx - Vírus Sincicial Respiratório",
        "Covidflursvgx - Vï¿½rus Sincicial Respiratï¿½rio",
        "Virusmol, Vírus Sincicial Respiratório",
        "Virusmol, Vï¿½rus Sincicial Respiratï¿½rio",
        "Vï¿½rus Sincial Respiratï¿½rio",
        "Vírus Sincial Respiratório",
        "Vírus respiratório - Sincicial",
        "Vï¿½rus respiratï¿½rio - Sincicial",
        "Vírus respiratórios - Vírus Sincicial Respira",
    },
    "SC2": {
        "Covid 19, Antígeno, teste rápido",
        "Covid 19, Antï¿½geno, teste rï¿½pido",
        "Covid 19, Detecção por PCR",
        "Covid 19, Detecï¿½ï¿½o por PCR",
        "Covidflursvgx - SARS-CoV-2",
        "Virusmol, SARS-CoV-2",
    },
    "META": {"Virusmol, Metapneumovírus Humano", "Virusmol, Metapneumovï¿½rus Humano"},
    "PARA": {
        "Virusmol, Parainfluenza 1",
        "Virusmol, Parainfluenza 2",
        "Virusmol, Parainfluenza 3",
        "Virusmol, Parainfluenza 4",
        "Vírus respiratórios - Parainfluenzavirus 1",
        "Vírus respiratórios - Parainfluenzavirus 2",
        "Vírus respiratórios - Parainfluenzavirus 3",
        "Vírus respiratórios - Parainfluenzavirus 4",
    },
    "ADENO": {
        "Virusmol, Adenovírus",
        "Virusmol, Adenovï¿½rus",
        "Vírus respiratórios - Adenovírus",
    },
    "COVS": {
        "Virusmol, Coronavírus 229E",
        "Virusmol, Coronavï¿½rus 229E",
        "Virusmol, Coronavírus HKU1",
        "Virusmol, Coronavï¿½rus HKU1",
        "Virusmol, Coronavírus NL63",
        "Virusmol, Coronavï¿½rus NL63",
        "Virusmol, Coronavírus OC43",
        "Virusmol, Coronavï¿½rus OC43",
    },
    "RINO": {"Virusmol, Rinovï¿½rus/Enterovï¿½rus", "Virusmol, Rinovírus/Enterovírus"},
    "ENTERO": {},
    "BOCA": {},
    "BAC": {
        "Virusmol, Bordetella parapertussis",
        "Virusmol, Bordetella pertussis",
        "Virusmol, Chlamydophila pneumoniae",
        "Virusmol, Mycoplasma pneumoniae",
    },
}


for pathogen, parameter_list in PATHOGEN_NORMALIZATION_DICT.items():
    test_result = pathogen + "_test_result"

    df_fleury_fixed[test_result] = df_fleury_fixed["RESULTADO"].where(
        df_fleury_fixed["PATOGENO"].isin(parameter_list), "NT"
    )

In [25]:
df_fleury_fixed

,CODIGO REQUISICAO,DATA COLETA,PACIENTE,SEXO,IDADE,MUNICIPIO,ESTADO,EXAME,PATOGENO,RESULTADO,...,VSR_test_result,SC2_test_result,META_test_result,PARA_test_result,ADENO_test_result,COVS_test_result,RINO_test_result,ENTERO_test_result,BOCA_test_result,BAC_test_result
0,1000964200_500,31/07/2023,F7631D38436612E1B04DF63D552E0D8E,F,29,COTIA,SP,2019NCOV,"Covid 19, Detecção por PCR",Neg,...,NT,Neg,NT,NT,NT,NT,NT,NT,NT,NT
1,1421754470_800,31/07/2023,06EEE3655339C91C09D6F8B45FE24A3B,M,67,SAO PAULO,SP,2019NCOV,"Covid 19, Detecção por PCR",Neg,...,NT,Neg,NT,NT,NT,NT,NT,NT,NT,NT
2,1421754512_200,31/07/2023,DA77C19BF2BBA8928A78EB95EC3DB44B,F,51,SAO PAULO,SP,2019NCOV,"Covid 19, Detecção por PCR",Neg,...,NT,Neg,NT,NT,NT,NT,NT,NT,NT,NT
3,1421754547_100,31/07/2023,0A6A0B135E017233C2A233E2A3C299B2,M,69,SAO PAULO,SP,2019NCOV,"Covid 19, Detecção por PCR",Neg,...,NT,Neg,NT,NT,NT,NT,NT,NT,NT,NT
4,1421754569_100,31/07/2023,27281A15BB1CFFEF5771DE1E69DC69EE,F,34,SAO PAULO,SP,2019NCOV,"Covid 19, Detecção por PCR",Neg,...,NT,Neg,NT,NT,NT,NT,NT,NT,NT,NT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293137,7600227856_1800,09/07/2023,B6D9786CDE6BA7A40E23939FCF800CF7,F,1,SAO PAULO,SP,VIRUSMOL,"Virusmol, Bordetella parapertussis",Neg,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,Neg
1293138,7600227856_1800,09/07/2023,B6D9786CDE6BA7A40E23939FCF800CF7,F,1,SAO PAULO,SP,VIRUSMOL,"Virusmol, Bordetella pertussis",Neg,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,Neg
1293139,7600227856_1800,09/07/2023,B6D9786CDE6BA7A40E23939FCF800CF7,F,1,SAO PAULO,SP,VIRUSMOL,"Virusmol, Chlamydophila pneumoniae",Neg,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,Neg
1293140,7600227856_1800,09/07/2023,B6D9786CDE6BA7A40E23939FCF800CF7,F,1,SAO PAULO,SP,VIRUSMOL,"Virusmol, SARS-CoV-2",Neg,...,NT,Neg,NT,NT,NT,NT,NT,NT,NT,NT
1293141,4250063876_100,05/07/2023,851A7C829F6D4F1DCAC6936622B5994E,F,0,SAO CAETANO DO SUL,SP,VRSAG,Vírus Sincial Respiratório,Neg,...,Neg,NT,NT,NT,NT,NT,NT,NT,NT,NT

### Criando coluna test_kit

In [26]:
df_fleury_fixed.fillna("N").query("PATOGENO.str.startswith('Covid 19')")[['PATOGENO', 'EXAME']].groupby("PATOGENO").agg({"EXAME": "unique"})

                                                                                EXAME
PATOGENO
Covid 19, Antígeno, teste rápido                                          [AGCOVIDNS]
Covid 19, Antï¿½geno, teste rï¿½pido                                      [AGCOVIDNS]
Covid 19, Detecção por PCR            [2019NCOV, COVID19GX, COVID19SALI, COVID19POCT]
Covid 19, Detecï¿½ï¿½o por PCR                     [2019NCOV, COVID19GX, COVID19SALI]

In [27]:
EXAMS_COVID_PCR = {
    "2019NCOV",
    "COVID19GX",
    "COVID19SALI",
    "COVID19POCT",
    "2019NCOV",
    "COVID19GX",
    "COVID19SALI",
}

EXAMS_COVID_ANTIGEN = {"AGCOVIDNS"}

# AGINFLU - flu_antigen
# AGSINCURG - vsr_antigen
# INFLUENZAPCR - flu_pcr
# COVIDFLURSVGX - test_4
# VIRUSMOL - test_21
# VRSAG - vsr_antigen

df_fleury_fixed["test_kit"] = df_fleury_fixed["EXAME"].apply(
    lambda x: 
    "flu_antigen"
    if x == "AGINFLU"
    else "vsr_antigen"
    if x in {"AGSINCURG", "VRSAG"}
    else "flu_pcr"
    if x == "INFLUENZAPCR"
    else "test_4"
    if x == "COVIDFLURSVGX"
    else "test_21"
    if x == "VIRUSMOL"
    else "covid_pcr"
    if x in EXAMS_COVID_PCR
    else "covid_antigen"
    if x in EXAMS_COVID_ANTIGEN
    else "unknown"
)

In [28]:
df_fleury_fixed.columns

Index(['CODIGO REQUISICAO', 'DATA COLETA', 'PACIENTE', 'SEXO', 'IDADE',
       'MUNICIPIO', 'ESTADO', 'EXAME', 'PATOGENO', 'RESULTADO',
       'FLUA_test_result', 'FLUB_test_result', 'VSR_test_result',
       'SC2_test_result', 'META_test_result', 'PARA_test_result',
       'ADENO_test_result', 'COVS_test_result', 'RINO_test_result',
       'ENTERO_test_result', 'BOCA_test_result', 'BAC_test_result',
       'test_kit'],
      dtype='object')

In [29]:
df_fleury_fixed = df_fleury_fixed.drop(columns=['PATOGENO', 'EXAME', 'RESULTADO']) # [WIP] Rename Columns

In [30]:
df_fleury_fixed

,CODIGO REQUISICAO,DATA COLETA,PACIENTE,SEXO,IDADE,MUNICIPIO,ESTADO,RESULTADO,FLUA_test_result,FLUB_test_result,...,SC2_test_result,META_test_result,PARA_test_result,ADENO_test_result,COVS_test_result,RINO_test_result,ENTERO_test_result,BOCA_test_result,BAC_test_result,test_kit
0,1000964200_500,31/07/2023,F7631D38436612E1B04DF63D552E0D8E,F,29,COTIA,SP,Neg,NT,NT,...,Neg,NT,NT,NT,NT,NT,NT,NT,NT,covid_pcr
1,1421754470_800,31/07/2023,06EEE3655339C91C09D6F8B45FE24A3B,M,67,SAO PAULO,SP,Neg,NT,NT,...,Neg,NT,NT,NT,NT,NT,NT,NT,NT,covid_pcr
2,1421754512_200,31/07/2023,DA77C19BF2BBA8928A78EB95EC3DB44B,F,51,SAO PAULO,SP,Neg,NT,NT,...,Neg,NT,NT,NT,NT,NT,NT,NT,NT,covid_pcr
3,1421754547_100,31/07/2023,0A6A0B135E017233C2A233E2A3C299B2,M,69,SAO PAULO,SP,Neg,NT,NT,...,Neg,NT,NT,NT,NT,NT,NT,NT,NT,covid_pcr
4,1421754569_100,31/07/2023,27281A15BB1CFFEF5771DE1E69DC69EE,F,34,SAO PAULO,SP,Neg,NT,NT,...,Neg,NT,NT,NT,NT,NT,NT,NT,NT,covid_pcr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293137,7600227856_1800,09/07/2023,B6D9786CDE6BA7A40E23939FCF800CF7,F,1,SAO PAULO,SP,Neg,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,Neg,test_21
1293138,7600227856_1800,09/07/2023,B6D9786CDE6BA7A40E23939FCF800CF7,F,1,SAO PAULO,SP,Neg,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,Neg,test_21
1293139,7600227856_1800,09/07/2023,B6D9786CDE6BA7A40E23939FCF800CF7,F,1,SAO PAULO,SP,Neg,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,Neg,test_21
1293140,7600227856_1800,09/07/2023,B6D9786CDE6BA7A40E23939FCF800CF7,F,1,SAO PAULO,SP,Neg,NT,NT,...,Neg,NT,NT,NT,NT,NT,NT,NT,NT,test_21
1293141,4250063876_100,05/07/2023,851A7C829F6D4F1DCAC6936622B5994E,F,0,SAO CAETANO DO SUL,SP,Neg,NT,NT,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,vsr_antigen

In [40]:
def aggregate_results_cython(df, test_id_columns, test_result_columns):
    """
    Aggregates the test results from a single test into a single row.
    Using the specified test_id_columns as the grouping columns.

    The test results in the test_result_columns should be either 'Pos', 'Neg', or 'NT'.

    The final result is 'Pos' if any of the tests was positive.
    'Neg' if none of the tests was positive and at least one was negative.
    'NT' if all of the tests were not performed.

    Args:
        df (pandas DataFrame): dataframe to be fixed
        test_id_columns (list of str): list of columns to be used as grouping columns
        test_result_columns (list of str): list of columns to be aggregated

    Returns:
        pandas DataFrame: dataframe with aggregated results
    """

    df_test_results = (
        df[test_id_columns + test_result_columns]
        .copy()

        # Mapping the test results to 1, 0, -1
        # and using the max to aggregate to improve performance
        .assign(
            **{
                test_result_column: df[test_result_column].map( {"Pos": 1, "Neg":0 , "NT": -1} )
                for test_result_column in test_result_columns
            }
        )
        .groupby(test_id_columns)
        .agg(
            {
                # test_result_column: at_least_one_positive
                test_result_column: 'max'
                for test_result_column in test_result_columns
            }
        )

    )

    # Join the aggregated test results back with the original dataframe
    df = df.drop(columns=test_result_columns).merge(
        df_test_results, on=test_id_columns, how="inner"
    )

    # map back the test results
    df = df.assign(
        **{
            test_result_column: df[test_result_column].map( {1: "Pos", 0: "Neg", -1: "NT"} )
            for test_result_column in test_result_columns
        }
    )

    return df


df_fleury_agg = aggregate_results_cython(
    df_fleury_fixed,
    ["CODIGO REQUISICAO", "test_kit"],
    [
        "FLUB_test_result",
        "FLUA_test_result",
        "VSR_test_result",
        "SC2_test_result",
        "META_test_result",
        "RINO_test_result",
        "PARA_test_result",
        "ADENO_test_result",
        "BOCA_test_result",
        "COVS_test_result",
        "ENTERO_test_result",
        "BAC_test_result",
    ],
)

In [46]:
df_fleury.query("`CODIGO REQUISICAO` == '1000859507_300'")

,CODIGO REQUISICAO,DATA COLETA,PACIENTE,SEXO,IDADE,MUNICIPIO,ESTADO,EXAME,PATOGENO,RESULTADO
264366,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Adenovírus",NEGATIVO
264367,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Coronavírus 229E",NEGATIVO
264368,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Coronavírus HKU1",NEGATIVO
264369,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Coronavírus NL63",NEGATIVO
264370,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Coronavírus OC43",NEGATIVO
264371,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Metapneumovírus Humano",NEGATIVO
264372,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Rinovírus/Enterovírus",NEGATIVO
264373,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Influenza A",NEGATIVO
264374,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Influenza A/H1",NEGATIVO
264375,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Influenza A/H1-2009",NEGATIVO
264376,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Influenza A/H3",NEGATIVO
264377,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Influenza B",NEGATIVO
264378,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Parainfluenza 1",NEGATIVO
264379,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Parainfluenza 2",NEGATIVO
264380,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Parainfluenza 3",NEGATIVO
264381,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Parainfluenza 4",NEGATIVO
264382,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Vírus Sincicial Respiratório",NEGATIVO
264383,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Bordetella parapertussis",NEGATIVO
264384,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Bordetella pertussis",NEGATIVO
264385,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, Chlamydophila pneumoniae",NEGATIVO
264386,1000859507_300,18/01/2022,B2317EE5F6373105488ABD0D96DB5005,M,50,COTIA,SP,VIRUSMOL,"Virusmol, SARS-CoV-2",POSITIVO

In [44]:
df_fleury_agg.query("`CODIGO REQUISICAO` == '1000859507_300'")[ [c for c in df_fleury_agg.columns if c.endswith("_result")] ]

,FLUB_test_result,FLUA_test_result,VSR_test_result,SC2_test_result,META_test_result,RINO_test_result,PARA_test_result,ADENO_test_result,BOCA_test_result,COVS_test_result,ENTERO_test_result,BAC_test_result
1225697,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225698,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225699,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225700,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225701,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225702,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225703,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225704,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225705,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225706,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225707,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225708,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225709,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225710,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225711,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225712,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225713,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225714,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225715,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225716,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg
1225717,Neg,Neg,Neg,Pos,Neg,Neg,Neg,Neg,NT,Neg,NT,Neg

In [49]:
df_fleury_agg.drop_duplicates(subset=['CODIGO REQUISICAO', 'test_kit'], keep='first')

,CODIGO REQUISICAO,DATA COLETA,PACIENTE,SEXO,IDADE,MUNICIPIO,ESTADO,RESULTADO,test_kit,FLUB_test_result,...,VSR_test_result,SC2_test_result,META_test_result,RINO_test_result,PARA_test_result,ADENO_test_result,BOCA_test_result,COVS_test_result,ENTERO_test_result,BAC_test_result
0,1000964200_500,31/07/2023,F7631D38436612E1B04DF63D552E0D8E,F,29,COTIA,SP,Neg,covid_pcr,NT,...,NT,Neg,NT,NT,NT,NT,NT,NT,NT,NT
1,1421754470_800,31/07/2023,06EEE3655339C91C09D6F8B45FE24A3B,M,67,SAO PAULO,SP,Neg,covid_pcr,NT,...,NT,Neg,NT,NT,NT,NT,NT,NT,NT,NT
2,1421754512_200,31/07/2023,DA77C19BF2BBA8928A78EB95EC3DB44B,F,51,SAO PAULO,SP,Neg,covid_pcr,NT,...,NT,Neg,NT,NT,NT,NT,NT,NT,NT,NT
3,1421754547_100,31/07/2023,0A6A0B135E017233C2A233E2A3C299B2,M,69,SAO PAULO,SP,Neg,covid_pcr,NT,...,NT,Neg,NT,NT,NT,NT,NT,NT,NT,NT
4,1421754569_100,31/07/2023,27281A15BB1CFFEF5771DE1E69DC69EE,F,34,SAO PAULO,SP,Neg,covid_pcr,NT,...,NT,Neg,NT,NT,NT,NT,NT,NT,NT,NT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1402039,8705576488_100,08/07/2023,5CF644BD5D258D8467E0E46CF445AE2C,F,79,SAO PAULO,SP,Neg,test_21,Neg,...,Neg,Neg,Pos,Neg,Neg,Neg,NT,Neg,NT,Neg
1402060,8705576490_100,08/07/2023,F995C9FFEDB3932CFB01B5F366A27A1E,M,79,SAO PAULO,SP,Neg,test_21,Neg,...,Neg,Neg,Pos,Neg,Neg,Neg,NT,Neg,NT,Neg
1402081,4580415318_200,09/07/2023,552B1BB28656EC3F81DFEC63F8D073E3,M,67,SAO BERNARDO DO CAMPO,SP,Neg,test_21,Neg,...,Neg,Neg,Pos,Neg,Neg,Neg,NT,Neg,NT,Neg
1402102,7600227856_1800,09/07/2023,B6D9786CDE6BA7A40E23939FCF800CF7,F,1,SAO PAULO,SP,Neg,test_21,Neg,...,Neg,Neg,Neg,Neg,Neg,Neg,NT,Pos,NT,Neg
1402123,4250063876_100,05/07/2023,851A7C829F6D4F1DCAC6936622B5994E,F,0,SAO CAETANO DO SUL,SP,Neg,vsr_antigen,NT,...,Neg,NT,NT,NT,NT,NT,NT,NT,NT,NT

In [50]:
df_fleury_agg.count()

CODIGO REQUISICAO     1056300
DATA COLETA           1056300
PACIENTE              1056300
SEXO                  1056300
IDADE                 1056300
MUNICIPIO             1056300
ESTADO                1056300
RESULTADO             1056300
test_kit              1056300
FLUB_test_result      1056300
FLUA_test_result      1056300
VSR_test_result       1056300
SC2_test_result       1056300
META_test_result      1056300
RINO_test_result      1056300
PARA_test_result      1056300
ADENO_test_result     1056300
BOCA_test_result      1056300
COVS_test_result      1056300
ENTERO_test_result    1056300
BAC_test_result       1056300
dtype: int64