In [1]:
import pandas as pd
import numpy as np

In [2]:
df_sabin_covid = pd.read_excel(
    './../data/SABIN/20230711_SABIN_Covid_2023ateSE33.xlsx'
)
df_sabin_covid.head(2)

,OS,Código Posto,Estado,Municipio,DataAtendimento,DataNascimento,Sexo,Descricao,Parametro,Resultado,DataAssinatura
0,321-66464-12445,321,DISTRITO FEDERAL,BRASÍLIA,21/12/2022,17/11/1980,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,NÃO DETECTADO (Ausência de RNA específico de S...,2023-01-01 00:00:00
1,525-66472-8612,525,DISTRITO FEDERAL,BRASÍLIA,29/12/2022,26/11/1983,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,DETECTADO (Presença de RNA específico de SARS-...,2023-01-01 00:00:00

In [3]:
df_sabin_covid\
    .groupby(['OS', 'Parametro'])\
    .agg({'Parametro': 'count'})\
    .query("Parametro > 1")

df_dict = pd.read_excel(
    './../data/SABIN/20230711_SABIN_paineis_2023ateSE27.xlsx', 
    index_col=None, header=0, 
    sheet_name=None, 
    dtype='str'
)

df_paineis = pd.DataFrame()
for sheet in df_dict.keys():
    df_paineis = df_paineis.append(df_dict[sheet].assign(ExcelSheet=sheet))

In [ ]:
# python scripts/reformat_sabin.py --datadir data --rename data/rename_columns.xlsx --correction data/fix_values.xlsx --output combined_sabin.tsv

In [6]:
df_sabin_result = pd.read_csv( '../combined_sabin.tsv', sep='\t' )

In [10]:
df_sabin_result['date_testing'].max()

'2023-08-20'

In [2]:
import pandas as pd

In [3]:
df_sabin_covid_csv = pd.read_csv('../data/SABIN/_out_csv/20230823_SABIN_Covid_2023ateSE33.xlsx - 2023.csv')

In [4]:
df_sabin_result = pd.read_csv( '../results/combined.tsv', sep='\t' ).query("lab_id == 'SABIN'")

In [34]:
df_sabin_covid_consulta = (
    df_sabin_covid_csv
    .query("Parametro not in ('RDRPCI', 'NALVOCI', 'NALVOCQ', 'NALVOCTL', 'RDRPALVOCTL')")
    .query("Parametro not in ('GENES', 'GENERDRP', 'GENEN')")
    .query("Parametro not in ('PCRESPSL', 'PCRVRESP')")
    .query("DataAtendimento == '7/7/2023'").sort_values('OS')
)

df_sabin_result.query("date_testing.str.contains('2023-07-07') and test_kit.str.contains('covid')", engine='python')

,OS,Código Posto,Estado,Municipio,DataAtendimento,DataNascimento,Sexo,Descricao,Parametro,Resultado,DataAssinatura
72429,001-66662-11959,1,DISTRITO FEDERAL,BRASÍLIA,7/7/2023,9/2/1971,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,NÃO DETECTADO (Ausência de RNA específico de S...,8/7/2023
72432,001-66662-11959,1,DISTRITO FEDERAL,BRASÍLIA,7/7/2023,9/2/1971,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,RDRPALVO,NÃO DETECTADO,8/7/2023
72525,001-66662-15146,1,DISTRITO FEDERAL,BRASÍLIA,7/7/2023,12/8/1974,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,DETECTADO (Presença de RNA específico de SARS-...,8/7/2023
72392,022-66662-10861,22,DISTRITO FEDERAL,BRASÍLIA,7/7/2023,27/06/1982,Masculino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,NÃO DETECTADO (Ausência de RNA específico de S...,8/7/2023
72395,022-66662-10861,22,DISTRITO FEDERAL,BRASÍLIA,7/7/2023,27/06/1982,Masculino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,RDRPALVO,NÃO DETECTADO,8/7/2023
...,...,...,...,...,...,...,...,...,...,...,...
72533,977-66662-15585,977,DISTRITO FEDERAL,BRASÍLIA,7/7/2023,12/2/1963,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,NÃO DETECTADO (Ausência de RNA específico de S...,8/7/2023
72357,977-66662-9996,977,DISTRITO FEDERAL,BRASÍLIA,7/7/2023,15/09/1986,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,NÃO DETECTADO (Ausência de RNA específico de S...,8/7/2023
72360,977-66662-9996,977,DISTRITO FEDERAL,BRASÍLIA,7/7/2023,15/09/1986,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,RDRPALVO,NÃO DETECTADO,8/7/2023
72227,991-66662-16811,991,PARANÁ,LONDRINA,7/7/2023,21/01/1990,Feminino,DETECCAO QUALITATIVA DE ANTIGENOS DE SARS-CoV-2,COVIDECO,DETECTADO,7/7/2023
72234,991-66662-18112,991,PARANÁ,LONDRINA,7/7/2023,25/04/1981,Feminino,DETECCAO QUALITATIVA DE ANTIGENOS DE SARS-CoV-2,COVIDECO,NÃO DETECTADO,7/7/2023

,lab_id,test_id,test_kit,patient_id,sample_id,state,location,date_testing,epiweek,age,...,Ct_RDRP,geneS_detection,META_test_result,RINO_test_result,PARA_test_result,ADENO_test_result,BOCA_test_result,COVS_test_result,ENTERO_test_result,BAC_test_result
8789,SABIN,001-66662-11959,covid_pcr,NaN,1d5874043e3914dd,Distrito Federal,BRASÍLIA,2023-07-07,2023-07-08,52,...,NaN,NaN,NT,NT,NT,NT,NT,NT,NT,NT
8790,SABIN,001-66662-15146,covid_pcr,NaN,fe9e1b464abaac68,Distrito Federal,BRASÍLIA,2023-07-07,2023-07-08,48,...,NaN,NaN,NT,NT,NT,NT,NT,NT,NT,NT
21547,SABIN,022-66662-10861,covid_pcr,NaN,240a1b497c6f7960,Distrito Federal,BRASÍLIA,2023-07-07,2023-07-08,41,...,NaN,NaN,NT,NT,NT,NT,NT,NT,NT,NT
27397,SABIN,027-66662-14866,covid_pcr,NaN,b7c23b41b6f1476f,Distrito Federal,BRASÍLIA,2023-07-07,2023-07-08,19,...,NaN,NaN,NT,NT,NT,NT,NT,NT,NT,NT
27398,SABIN,027-66662-9666,covid_pcr,NaN,c111c875371ed8b5,Distrito Federal,BRASÍLIA,2023-07-07,2023-07-08,59,...,NaN,NaN,NT,NT,NT,NT,NT,NT,NT,NT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
693207,SABIN,972-66662-16077,covid_antigen,NaN,0ea394961eb5f2e2,São Paulo,CAMPINAS,2023-07-07,2023-07-08,43,...,NaN,NaN,NT,NT,NT,NT,NT,NT,NT,NT
694913,SABIN,977-66662-15585,covid_pcr,NaN,0c06e1aebe68655f,Distrito Federal,BRASÍLIA,2023-07-07,2023-07-08,60,...,NaN,NaN,NT,NT,NT,NT,NT,NT,NT,NT
694914,SABIN,977-66662-9996,covid_pcr,NaN,ab2219c3d36420c2,Distrito Federal,BRASÍLIA,2023-07-07,2023-07-08,36,...,NaN,NaN,NT,NT,NT,NT,NT,NT,NT,NT
695819,SABIN,991-66662-16811,covid_antigen,NaN,0f1da355dd12028c,Paraná,LONDRINA,2023-07-07,2023-07-08,33,...,NaN,NaN,NT,NT,NT,NT,NT,NT,NT,NT
695820,SABIN,991-66662-18112,covid_antigen,NaN,d037b53d8d8b295b,Paraná,LONDRINA,2023-07-07,2023-07-08,42,...,NaN,NaN,NT,NT,NT,NT,NT,NT,NT,NT

## Duplicatas

In [4]:
df_duplicates_covid = (
    df_sabin_covid
    .assign( one=1 )
    .groupby(['OS', 'Parametro'])
    .agg(count=('one', 'sum'))
    .query("count > 1")
    .assign(count=lambda x: x['count']-1)
)

df_duplicates_covid['count'].sum()

7

In [5]:
df_duplicates_paineis = (
    df_paineis
    .groupby(['OS', 'Parametro'])
    .agg(count=('Parametro', 'count'))
    .query("count > 1")
    .assign(count=lambda x: x['count']-1)
)

df_duplicates_paineis['count'].sum()

393

In [38]:
df_full = pd.concat([df_sabin_covid, df_paineis])
df_full.query("OS == '1565-66582-17959'")

,OS,Código Posto,Estado,Municipio,DataAtendimento,DataNascimento,Sexo,Descricao,Parametro,Resultado,DataAssinatura,ExcelSheet
44732,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,NÃO DETECTADO (Ausência de RNA específico de S...,20/04/2023,NaN
1761,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,INFLUA,0,20/04/2023,RESPIRA
1762,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,NL63,0,20/04/2023,RESPIRA
1763,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,OC43,0,20/04/2023,RESPIRA
1764,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,HRV,0,20/04/2023,RESPIRA
1765,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,INFLUB,0,20/04/2023,RESPIRA
1766,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,H1N1R,0,20/04/2023,RESPIRA
1767,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,COR229E,0,20/04/2023,RESPIRA
1768,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,HPIV3,0,20/04/2023,RESPIRA
1769,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,HPIV2,0,20/04/2023,RESPIRA
1770,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,HPIV4,0,20/04/2023,RESPIRA
1771,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,HPIV1,0,20/04/2023,RESPIRA
1772,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,MPVR,0,20/04/2023,RESPIRA
1773,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,HBOV,Bocavírus,20/04/2023,RESPIRA
1774,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,MP,0,20/04/2023,RESPIRA
1775,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,HEVR,0,20/04/2023,RESPIRA
1776,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,ADEV,0,20/04/2023,RESPIRA
1777,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,H3,0,20/04/2023,RESPIRA
1778,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,H1PDM09,0,20/04/2023,RESPIRA
1779,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,RSVA,0,20/04/2023,RESPIRA
1780,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,RSVB,0,20/04/2023,RESPIRA
1781,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,CP,0,20/04/2023,RESPIRA
1782,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,LP,0,20/04/2023,RESPIRA
1783,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,BP,0,20/04/2023,RESPIRA
1784,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,BPP,0,20/04/2023,RESPIRA
1785,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,HI,0,20/04/2023,RESPIRA
1786,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,SP,0,20/04/2023,RESPIRA
1787,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,RESPIRA,0,20/04/2023,RESPIRA
1788,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,RESPIRA1,NÃO DETECTADO,20/04/2023,RESPIRA
1789,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,RESPIRA2,NÃO DETECTADO,20/04/2023,RESPIRA
1790,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,RESPIRA3,HBoV,20/04/2023,RESPIRA
1791,1565-66582-17959,1565,DISTRITO FEDERAL,BRASÍLIA,18/04/2023,20/02/1933,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,RESPIRA4,NÃO DETECTADO,20/04/2023,RESPIRA

In [7]:
df_full = pd.concat([df_sabin_covid, df_paineis])

df_duplicates_os_full = (
    df_full
    .drop_duplicates(subset=['OS', 'Parametro'])
    .query("Parametro not in ('PCRESPSL', 'PCRVRESP')")
    .query("Parametro not in ('GENES', 'GENERDRP', 'GENEN')")
    .query("Parametro not in ('RESPIRA1', 'RESPIRA2', 'RESPIRA3', 'RESPIRA4')")
    .assign( one=1 )
    .groupby(['OS'])
    .agg(count=('one', 'sum'))
    .query("count > 1")
    .assign(count=lambda x: x['count']-1)
)


df_duplicates_os_full.sort_values('count', ascending=False).shape

(1928, 1)

In [8]:
df_duplicates_os_full.duplicated().sum()

1918

In [9]:
df_full.query("OS == '541-66549-12852'")

,OS,Código Posto,Estado,Municipio,DataAtendimento,DataNascimento,Sexo,Descricao,Parametro,Resultado,DataAssinatura,ExcelSheet
614,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,INFLUA,Influenza A,17/03/2023,RESPIRA
615,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,NL63,0,17/03/2023,RESPIRA
616,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,OC43,Coronavírus OC43,17/03/2023,RESPIRA
617,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,HRV,Rinovírus,17/03/2023,RESPIRA
618,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,INFLUB,0,17/03/2023,RESPIRA
619,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,H1N1R,0,17/03/2023,RESPIRA
620,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,COR229E,Coronavírus 229E,17/03/2023,RESPIRA
621,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,HPIV3,Parainfluenza 3,17/03/2023,RESPIRA
622,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,HPIV2,Parainfluenza 2,17/03/2023,RESPIRA
623,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,HPIV4,Parainfluenza 4,17/03/2023,RESPIRA
624,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,HPIV1,Parainfluenza 1,17/03/2023,RESPIRA
625,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,MPVR,Metapneumovírus,17/03/2023,RESPIRA
626,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,HBOV,Bocavírus,17/03/2023,RESPIRA
627,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,MP,0,17/03/2023,RESPIRA
628,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,HEVR,Enterovírus,17/03/2023,RESPIRA
629,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,ADEV,Adenovírus,17/03/2023,RESPIRA
630,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,H3,Influenza A H3N2,17/03/2023,RESPIRA
631,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,H1PDM09,Influenza A H1pdm09,17/03/2023,RESPIRA
632,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,RSVA,Sincicial Respiratório A,17/03/2023,RESPIRA
633,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,RSVB,Sincicial Respiratório B,17/03/2023,RESPIRA
634,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,CP,0,17/03/2023,RESPIRA
635,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,LP,0,17/03/2023,RESPIRA
636,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,BP,0,17/03/2023,RESPIRA
637,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,BPP,0,17/03/2023,RESPIRA
638,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,HI,Haemophilus influenzae,17/03/2023,RESPIRA
639,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,SP,Streptococcus pneumoniae,17/03/2023,RESPIRA
640,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,RESPIRA,0,17/03/2023,RESPIRA
641,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,RESPIRA1,"RSV A, Flu A, RSV B, Flu A-H1pdm09, Flu A-H3",17/03/2023,RESPIRA
642,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,RESPIRA2,"PIV4, MPV, PIV2, PIV1, AdV, HEV, PIV3",17/03/2023,RESPIRA
643,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,RESPIRA3,"OC43, HBoV, 229E, HRV",17/03/2023,RESPIRA
644,541-66549-12852,541,CONTROL LAB,CONTROL LAB,16/03/2023,1987-01-01 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,RESPIRA4,"SP, HI",17/03/2023,RESPIRA

In [10]:
df_paineis\
    .groupby([
        'OS',
        'Estado',
        'Municipio',
        'DataAtendimento',
        'Sexo',
        'Descricao',
        'Resultado',
    ] )\
    .agg({'Parametro': 'count'})\
    .query("Parametro > 21")\
    .reset_index()

,OS,Estado,Municipio,DataAtendimento,Sexo,Descricao,Resultado,Parametro
0,001-66571-1874,DISTRITO FEDERAL,BRASÍLIA,2023-07-04 00:00:00,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,0,24
1,001-66572-11405,DISTRITO FEDERAL,BRASÍLIA,2023-08-04 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,0,26
2,001-66576-19131,DISTRITO FEDERAL,BRASÍLIA,2023-12-04 00:00:00,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,0,26
3,001-66601-639,DISTRITO FEDERAL,BRASÍLIA,2023-07-05 00:00:00,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,0,24
4,001-66608-1378,DISTRITO FEDERAL,BRASÍLIA,14/05/2023,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,0,25
...,...,...,...,...,...,...,...,...
122,942-66636-2500,DISTRITO FEDERAL,BRASÍLIA,2023-11-06 00:00:00,Feminino,PAINEL MOLECULAR RAPIDO PARA INFECÇOES RESPIRA...,NÃO DETECTADO,40
123,946-66636-2510,DISTRITO FEDERAL,BRASÍLIA,2023-11-06 00:00:00,Masculino,PAINEL MOLECULAR RAPIDO PARA INFECÇOES RESPIRA...,NÃO DETECTADO,42
124,946-66637-7583,DISTRITO FEDERAL,BRASÍLIA,2023-12-06 00:00:00,Feminino,PAINEL MOLECULAR RAPIDO PARA INFECÇOES RESPIRA...,NÃO DETECTADO,42
125,947-66577-21066,DISTRITO FEDERAL,BRASÍLIA,13/04/2023,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,0,26
126,960-66629-1605,MINAS GERAIS,UBERLANDIA,2023-04-06 00:00:00,Masculino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,0,26

In [11]:
df_paineis\
    .assign( count = 1 )\
    .groupby([
        'OS',
        'Estado',
        'Municipio',
        'DataAtendimento',
        'Sexo',
        'Resultado',
        'Parametro'
    ] )\
    .agg( count = ('count', 'sum') )\
    .query("count > 1")\
    ['count'].sum()

786

In [12]:
df_sabin_covid\
    .assign( count = 1 )\
    .groupby([
        'OS',
        'Estado',
        'Municipio',
        'DataAtendimento',
        'Sexo',
        'Resultado',
        'Parametro'
    ] )\
    .agg( count = ('count', 'sum') )\
    .query("count > 1")\
    ['count'].sum()

12

In [13]:
df_paineis[['OS', 'Parametro']].drop_duplicates().groupby('OS').count()

                 Parametro
OS
001-66478-14288          8
001-66495-13038          8
001-66505-15525         21
001-66512-16646         21
001-66513-20883          8
...                    ...
977-66631-13550          8
977-66634-18244          8
977-66646-14751          8
977-66649-11555          8
977-66658-18375          8

[1618 rows x 1 columns]

In [14]:
df_sabin_covid\
    .groupby('Parametro')\
    .agg({'Parametro': 'count'})

             Parametro
Parametro
COVIDECO         17607
NALVO            48642
NALVOCI             54
NALVOCQ             55
NALVOCTL            56
NALVOSSA          1597
PCRSALIV           891
RDRPALVO            54
RDRPALVOCTL         57
RDRPCI              55
TMR19RES1         3716

In [15]:
df_sabin_covid.groupby('OS').agg({'Parametro': lambda x: ','.join(x), 'OS': 'count'}).query("'NALVOSSA' in Parametro and OS > 1")

Empty DataFrame
Columns: [Parametro, OS]
Index: []

In [16]:
df_sabin_covid['Parametro'].unique()

array(['NALVO', 'PCRSALIV', 'COVIDECO', 'TMR19RES1', 'NALVOSSA',
       'NALVOCTL', 'RDRPALVOCTL', 'RDRPALVO', 'RDRPCI', 'NALVOCI',
       'NALVOCQ'], dtype=object)

In [17]:
df_sabin_covid['Descricao'].unique()

array(['TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS SARS-CoV2',
       'TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS SARS-CoV-2 SALIVA',
       'DETECCAO QUALITATIVA DE ANTIGENOS DE SARS-CoV-2',
       'TESTE MOLECULAR PARA SARS-CoV-2 (COVID 19) COM AMPLIFICAÇÃO ISOTÉRMICA'],
      dtype=object)

In [18]:
df_sabin_covid['Parametro'].unique()

array(['NALVO', 'PCRSALIV', 'COVIDECO', 'TMR19RES1', 'NALVOSSA',
       'NALVOCTL', 'RDRPALVOCTL', 'RDRPALVO', 'RDRPCI', 'NALVOCI',
       'NALVOCQ'], dtype=object)

In [19]:
df_sabin_covid\
    .drop_duplicates(['Parametro', 'OS'])\
    .query("Parametro in ('NALVO')").shape

(48638, 11)

In [20]:
df_sabin_covid\
    .drop_duplicates(['Parametro', 'OS'])\
    .query("Parametro in ('RDRPALVO')").shape

(54, 11)

In [21]:
(
    df_sabin_covid
    .drop_duplicates(['Parametro', 'OS'])
    .query("Parametro in ('NALVO', 'RDRPALVO')")
    .pivot(index='OS', columns='Parametro', values='Resultado')
    .query("RDRPALVO == RDRPALVO")
)

Parametro,NALVO,RDRPALVO
OS,,
001-66662-11959,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
022-66662-10861,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
027-66662-14866,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
027-66662-9666,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
032-66610-16918,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
032-66662-11056,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
035-66662-13534,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
045-66662-10353,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
047-66610-22286,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
047-66662-15970,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
053-66662-16574,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
054-66662-10510,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
074-66662-9802,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
1068-66494-16398,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
122-66662-15239,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
145-66662-15064,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
145-66662-8386,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
145-66662-9529,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
145-66662-9708,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
145-66663-6392,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
1572-66662-12193,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
1611-66595-1747,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
174-66662-5695,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
177-66542-17753,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
206-66662-6409,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
221-66601-1861,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
221-66661-18951,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
221-66662-15131,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
223-66662-18558,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
223-66662-18728,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
225-66662-13455,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
237-66662-13627,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
242-66662-13260,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
340-66662-5140,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
397-66662-3227,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
413-66662-11660,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
430-66662-6190,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
436-66662-7974,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
492-66663-5271,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
562-66544-14822,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
830-66662-11840,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
830-66662-9236,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
833-66662-6870,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
848-66662-14161,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
863-66591-19146,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
887-66490-13536,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
901-66662-13008,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
939-66662-11549,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
939-66662-13340,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
944-66662-10723,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
944-66662-10813,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
944-66662-15966,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
944-66662-18759,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO
977-66662-9996,NÃO DETECTADO (Ausência de RNA específico de S...,NÃO DETECTADO

Sabin Paineis Virais

In [22]:
df_dict = pd.read_excel(
    './../data/SABIN/20230711_SABIN_paineis_2023ateSE27.xlsx', 
    index_col=None, header=0, 
    sheet_name=['PCRESPSL', 'PCRVRESP'], 
    dtype='str'
)
        
df = pd.DataFrame()
for sheet in df_dict.keys():
    df = df.append(df_dict[sheet].assign(ExcelSheet=sheet))

In [23]:
df.drop_duplicates(['Parametro', 'OS'])\
.query("Parametro in ('GENES', 'GENERDRP', 'GENEN', 'PCRVRESPBM')")\
.groupby('OS').agg({'OS': 'count'})\
.query("OS != 4")

                 OS
OS
001-66595-1732    1
047-66545-1328    1
151-66568-22111   1
321-66610-16322   1
321-66612-19967   1
321-66637-10046   1
321-66652-11464   1

In [24]:
df\
.query("OS in ('001-66595-1732', '047-66545-1328', '151-66568-22111','321-66610-16322', '321-66612-19967', '321-66637-10046','321-66652-11464')")\
.query("Parametro in ('GENES', 'GENERDRP', 'GENEN', 'PCRVRESPBM')")

,OS,Código Posto,Estado,Municipio,DataAtendimento,DataNascimento,Sexo,Descricao,Parametro,Resultado,DataAssinatura,ExcelSheet
1704,047-66545-1328,47,DISTRITO FEDERAL,BRASÍLIA,2023-12-03 00:00:00,29/08/1967,Masculino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",PCRVRESPBM,NÃO DETECTADO (Ausência de RNA viral específico),13/03/2023,PCRVRESP
2989,151-66568-22111,151,DISTRITO FEDERAL,BRASÍLIA,2023-04-04 00:00:00,1991-09-01 00:00:00,Masculino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",PCRVRESPBM,NÃO DETECTADO (Ausência de RNA viral específico),2023-06-04 00:00:00,PCRVRESP
5066,001-66595-1732,1,DISTRITO FEDERAL,BRASÍLIA,2023-01-05 00:00:00,27/06/1947,Feminino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",PCRVRESPBM,DETECTADO (Presença de RNA viral específico),2023-02-05 00:00:00,PCRVRESP
6487,321-66610-16322,321,DISTRITO FEDERAL,BRASÍLIA,16/05/2023,26/02/1948,Feminino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",PCRVRESPBM,NÃO DETECTADO (Ausência de RNA viral específico),19/05/2023,PCRVRESP
6820,321-66612-19967,321,DISTRITO FEDERAL,BRASÍLIA,18/05/2023,27/05/1932,Feminino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",PCRVRESPBM,DETECTADO (Presença de RNA viral específico),20/05/2023,PCRVRESP
9073,321-66637-10046,321,DISTRITO FEDERAL,BRASÍLIA,2023-12-06 00:00:00,1961-09-08 00:00:00,Feminino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",PCRVRESPBM,DETECTADO (Presença de RNA viral específico),14/06/2023,PCRVRESP
9990,321-66652-11464,321,DISTRITO FEDERAL,BRASÍLIA,27/06/2023,1953-10-05 00:00:00,Feminino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",PCRVRESPBM,NÃO DETECTADO (Ausência de RNA viral específico),28/06/2023,PCRVRESP

In [25]:
df['Parametro'].unique()

array(['PCRVRESPBM', 'PCRVRESPBM2', 'PCRVRESPBM3', 'PCRVRESPBM4', 'GENES',
       'GENERDRP', 'GENEN', 'PCRVRESP'], dtype=object)

In [26]:
df.drop_duplicates(['Parametro', 'OS'])\
.query("Parametro in ('GENES', 'GENERDRP', 'GENEN', 'PCRVRESPBM')")\
.pivot(index='OS', columns='Parametro', values='Resultado')\
.query("GENES == 'NÃO DETECTADO' or GENERDRP == 'NÃO DETECTADO' or GENEN == 'NÃO DETECTADO'")\
.query("not PCRVRESPBM.str.startswith('NÃO')", engine='python')
# 1350

Parametro,GENEN,GENERDRP,GENES,PCRVRESPBM
OS,,,,
047-66570-15906,NÃO DETECTADO,DETECTADO,DETECTADO,DETECTADO (Presença de RNA viral específico)
053-66599-21312,NÃO DETECTADO,DETECTADO,DETECTADO,DETECTADO (Presença de RNA viral específico)
086-66584-19599,DETECTADO,NÃO DETECTADO,DETECTADO,DETECTADO (Presença de RNA viral específico)
1417-66598-5930,NÃO DETECTADO,DETECTADO,NÃO DETECTADO,DETECTADO (Presença de RNA viral específico)
1574-66539-102,NÃO DETECTADO,NÃO DETECTADO,DETECTADO,DETECTADO (Presença de RNA viral específico)
1576-66538-2188,NÃO DETECTADO,NÃO DETECTADO,NÃO DETECTADO,DETECTADO (Presença de RNA viral específico)
221-66567-20127,NÃO DETECTADO,NÃO DETECTADO,DETECTADO,DETECTADO (Presença de RNA viral específico)
221-66610-21478,NÃO DETECTADO,DETECTADO,NÃO DETECTADO,DETECTADO (Presença de RNA viral específico)
321-66502-13918,NÃO DETECTADO,DETECTADO,DETECTADO,DETECTADO (Presença de RNA viral específico)
321-66624-20373,NÃO DETECTADO,NÃO DETECTADO,DETECTADO,DETECTADO (Presença de RNA viral específico)
446-66520-16759,DETECTADO,NÃO DETECTADO,DETECTADO,DETECTADO (Presença de RNA viral específico)
561-66485-18616,NÃO DETECTADO,DETECTADO,DETECTADO,DETECTADO (Presença de RNA viral específico)
977-66600-13314,NÃO DETECTADO,NÃO DETECTADO,DETECTADO,DETECTADO (Presença de RNA viral específico)

In [27]:
df_sabin = pd.read_excel(
    './../data/SABIN/20230711_SABIN_paineis_2023ateSE27.xlsx'
)
df_sabin['Descricao'].unique()

array(['PAINEL MOLECULAR RAPIDO PARA INFECÇOES RESPIRATORIAS COM SARSCOV2'],
      dtype=object)

In [28]:
# import combinations
from itertools import combinations, product

resultados = df_sabin['Resultado'].unique()
pathogens = [
    'FLUA','FLUB','VSR','META','RINO',
    'PARA','ADENO','BOCA','COVS','ENTERO','BAC'
]

pathogens_results = list(product (pathogens, resultados))
pathogens_results

df_pathogens_results = pd.DataFrame(pathogens_results, columns=['column_name', 'old_data'])
df_pathogens_results['column_name'] = df_pathogens_results['column_name'].apply(lambda x:  x + '_test_result')

df_pathogens_results['lab_id'] = 'SABIN'
df_pathogens_results['new_data'] = df_pathogens_results['old_data'].apply(
    lambda x: 'neg' if 'NÃO' in x else 'pos' 
) 

df_pathogens_results['new_data_2'] = df_pathogens_results['new_data'].apply(
    lambda x: 'Negative' if  x == 'neg' else 'Positive'
) 

df_pathogens_results

           column_name       old_data lab_id new_data new_data_2
0     FLUA_test_result  NÃO DETECTADO  SABIN      neg   Negative
1     FLUA_test_result      DETECTADO  SABIN      pos   Positive
2     FLUA_test_result  NÃO APLICÁVEL  SABIN      neg   Negative
3     FLUB_test_result  NÃO DETECTADO  SABIN      neg   Negative
4     FLUB_test_result      DETECTADO  SABIN      pos   Positive
5     FLUB_test_result  NÃO APLICÁVEL  SABIN      neg   Negative
6      VSR_test_result  NÃO DETECTADO  SABIN      neg   Negative
7      VSR_test_result      DETECTADO  SABIN      pos   Positive
8      VSR_test_result  NÃO APLICÁVEL  SABIN      neg   Negative
9     META_test_result  NÃO DETECTADO  SABIN      neg   Negative
10    META_test_result      DETECTADO  SABIN      pos   Positive
11    META_test_result  NÃO APLICÁVEL  SABIN      neg   Negative
12    RINO_test_result  NÃO DETECTADO  SABIN      neg   Negative
13    RINO_test_result      DETECTADO  SABIN      pos   Positive
14    RINO_test_result  NÃO APLICÁVEL  SABIN      neg   Negative
15    PARA_test_result  NÃO DETECTADO  SABIN      neg   Negative
16    PARA_test_result      DETECTADO  SABIN      pos   Positive
17    PARA_test_result  NÃO APLICÁVEL  SABIN      neg   Negative
18   ADENO_test_result  NÃO DETECTADO  SABIN      neg   Negative
19   ADENO_test_result      DETECTADO  SABIN      pos   Positive
20   ADENO_test_result  NÃO APLICÁVEL  SABIN      neg   Negative
21    BOCA_test_result  NÃO DETECTADO  SABIN      neg   Negative
22    BOCA_test_result      DETECTADO  SABIN      pos   Positive
23    BOCA_test_result  NÃO APLICÁVEL  SABIN      neg   Negative
24    COVS_test_result  NÃO DETECTADO  SABIN      neg   Negative
25    COVS_test_result      DETECTADO  SABIN      pos   Positive
26    COVS_test_result  NÃO APLICÁVEL  SABIN      neg   Negative
27  ENTERO_test_result  NÃO DETECTADO  SABIN      neg   Negative
28  ENTERO_test_result      DETECTADO  SABIN      pos   Positive
29  ENTERO_test_result  NÃO APLICÁVEL  SABIN      neg   Negative
30     BAC_test_result  NÃO DETECTADO  SABIN      neg   Negative
31     BAC_test_result      DETECTADO  SABIN      pos   Positive
32     BAC_test_result  NÃO APLICÁVEL  SABIN      neg   Negative

In [29]:
parameters = df_sabin['Parametro'].unique()

for parameter in parameters:
    print(parameter)

PARA1
PARA2
PARA3
PARA4
BORDETELLAP
VSINCICIAL
CPNEUMONIAE
ADEN
CORON
CORHKU
CORNL
CORC
HUMANMET
HUMANRH
INFLUEH
INFLUEN
INFLUENZ
INFLUEB
MYCOPAIN
PAINSARS
RSPAIN

In [30]:
df_sabin['Resultado'].unique()

array(['NÃO DETECTADO', 'DETECTADO', 'NÃO APLICÁVEL'], dtype=object)

In [31]:
df_sabin.groupby('Código Posto')['Código Posto'].count()
df_sabin.groupby('OS')['OS'].count()

OS
001-66505-15525    21
001-66512-16646    21
001-66596-20428    21
001-66599-21706    21
001-66611-20884    21
                   ..
948-66627-19486    21
952-66531-131      21
952-66611-22235    21
952-66612-21183    21
952-66664-1194     21
Name: OS, Length: 141, dtype: int64

In [32]:
df_sabin.drop_duplicates(subset=['OS', 'Parametro', 'DataAtendimento']).groupby('OS')['OS'].count().unique()

array([21])

In [33]:
df_sabin_covid.groupby('OS')['OS'].count().unique()

array([1, 2, 7])

**Fix**

In [34]:
df_rename_cols = pd.read_excel('./../data/rename_columns.xlsx')
df_fix_values = pd.read_excel('./../data/fix_values.xlsx')

In [35]:
df_fix_values.query("lab_id == 'SABIN' and column_name == 'SC2_test_result'")['old_data'].tolist()

[' NÃO DETECTADO',
 'DETECTADO',
 'DETECTADO (Presença de RNA específico de SARS-CoV-2)',
 'INDETERMINADO (Presença de RNA específico aos Sarbecovírus)',
 'NÃO DETECTADO',
 'Não detectado ',
 'NÃO DETECTADO (Ausência de RNA específico de SARS-CoV-2)',
 'NÃO APLICÁVEL',
 'REAGENTE',
 'NÃO DETECTADO (Ausência de RNA viral específico)',
 'DETECTADO (Presença de RNA viral específico)']

In [36]:
df_rename_cols.query("lab_id == 'SABIN'")

   lab_id      column_name      new_name other
68  SABIN            Idade           age   NaN
69  SABIN           Estado         state   NaN
70  SABIN   DataNascimento     birthdate   NaN
71  SABIN  DataAtendimento  date_testing   NaN
72  SABIN             Sexo           sex   NaN
73  SABIN               OS       test_id   NaN
74  SABIN        Municipio      location   NaN